### ISSUE TITLE
Create card component 

### ISSUE THREAD

**Issue by jbienesdev** [covid19zc/covid19zc-website#1]
Create a reusable Vue component that looks like this:

<img width="671" alt="image" src="https://user-images.githubusercontent.com/17470909/77552592-b1a6ec80-6eee-11ea-8e97-a9475efefb7e.png">

**Comment by JHNLWHD** [comment]
![image](https://user-images.githubusercontent.com/15794235/77854070-812abf80-721a-11ea-9b1f-0daa267d4393.png)

- The card looks good as designed in the mockup. The responsiveness issue is being fixed in #9.

QA Testing Passed 💯
