### ISSUE TITLE
Create divider and Hotline number header

### ISSUE THREAD

**Issue by jbienesdev** [covid19zc/covid19zc-website#13]
In the design, add a divider between the cards and the hotline numbers. Also, add the hotline number header with the appropriate margins.

<img width="828" alt="image" src="https://user-images.githubusercontent.com/17470909/77849460-50d52800-71fe-11ea-9f50-03e8201b7a6c.png">

**Comment by JHNLWHD** [comment]
![image](https://user-images.githubusercontent.com/15794235/78009867-3c1aa080-7374-11ea-949d-78fb2f640db9.png)

QA Testing Passed 💯
