### ISSUE TITLE
Change background color of page and cards

### ISSUE THREAD

**Issue by jbienesdev** [covid19zc/covid19zc-website#14]
Change background color of the page to `bg-gray-100` and the CardCounter to `bg-white` as seen on the mockup.

![Frontpage](https://user-images.githubusercontent.com/17470909/77849527-d953c880-71fe-11ea-849a-046f5b8c8d74.jpg)

**Comment by JHNLWHD** [comment]
![image](https://user-images.githubusercontent.com/15794235/78009995-6bc9a880-7374-11ea-983b-d8f638c5a092.png)

QA Testing Passed 💯
