### ISSUE TITLE
Create notification component

### ISSUE THREAD

**Issue by jbienesdev** [covid19zc/covid19zc-website#2]
Create this notification component at the topmost of the front page.

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/17470909/77633620-b02b0200-6f8a-11ea-8fd8-f6c3c9ce9209.png">

**Comment by JHNLWHD** [comment]
Desktop: 
![image](https://user-images.githubusercontent.com/15794235/77854009-28f3bd80-721a-11ea-8595-94c9e5e4aa88.png)

Mobile:
![image](https://user-images.githubusercontent.com/15794235/77854020-3610ac80-721a-11ea-919c-58556d9ff3ed.png)

QA Testing Passed 💯
