### ISSUE TITLE
Update Notification component

### ISSUE THREAD

**Issue by jbienesdev** [covid19zc/covid19zc-website#29]
Update Notification component to the current design and put the component inside `layouts/default.vue`

![image](https://user-images.githubusercontent.com/17470909/78418235-fbb96c00-766c-11ea-8d1d-53d5afb4553f.png)

**Comment by JHNLWHD** [comment]
![image](https://user-images.githubusercontent.com/15794235/78470591-621db780-775d-11ea-914f-f1163bf4b6bd.png)

QA Testing Passed 💯
