### ISSUE TITLE
Create accordion component

### ISSUE THREAD

**Issue by jbienesdev** [covid19zc/covid19zc-website#3]
Create a reusable accordion component that looks like this.

<img width="820" alt="image" src="https://user-images.githubusercontent.com/17470909/77634357-c4233380-6f8b-11ea-8a14-c5344024d572.png">

I suggest to use slots for the content inside the accordion. Just insert dummy content because I'll create another issue for it.

Default state should be `Open`

**Comment by jbienesdev** [comment]
Gonna take this issue.

**Comment by JHNLWHD** [comment]
**Default:**
![image](https://user-images.githubusercontent.com/15794235/77854410-df58a200-721c-11ea-934e-52054a373c32.png)

**Closed:**
![image](https://user-images.githubusercontent.com/15794235/77854427-f8f9e980-721c-11ea-9aff-78de71006cfc.png)

QA Testing Passed 💯
