### ISSUE TITLE
Update background color

### ISSUE THREAD

**Issue by jbienesdev** [covid19zc/covid19zc-website#30]
Update background color to `#FFF5F5`

![Red Version (1)](https://user-images.githubusercontent.com/17470909/78418260-33c0af00-766d-11ea-8e1b-8441238a0e00.jpg)

**Comment by JHNLWHD** [comment]
![image](https://user-images.githubusercontent.com/15794235/78470660-b3c64200-775d-11ea-80d2-e543d75050f8.png)

QA Testing Passed 💯
