### ISSUE TITLE
Create navigation component

### ISSUE THREAD

**Issue by jbienesdev** [covid19zc/covid19zc-website#31]
Create a separate navigation components as shown below with the nav links and active state

![image](https://user-images.githubusercontent.com/17470909/78418285-6bc7f200-766d-11ea-85f5-b94b81c08317.png)

**Comment by JHNLWHD** [comment]
![image](https://user-images.githubusercontent.com/15794235/78470633-95604680-775d-11ea-8dc3-37aa64d16969.png)

QA Testing Passed 💯
