### ISSUE TITLE
Change design of the card components as seen on the mockup

### ISSUE THREAD

**Issue by jbienesdev** [covid19zc/covid19zc-website#32]
Card container's width is 75% of the page and flex item's should have a class of `flex-1`

![image](https://user-images.githubusercontent.com/17470909/78418320-b3e71480-766d-11ea-921e-3bde290b436a.png)

![Red Version (1)](https://user-images.githubusercontent.com/17470909/78418260-33c0af00-766d-11ea-8e1b-8441238a0e00.jpg)

**Comment by JHNLWHD** [comment]
![image](https://user-images.githubusercontent.com/15794235/78470568-339fdc80-775d-11ea-8294-9e8fc08beeac.png)

QA Testing Passed 💯
