### ISSUE TITLE
Redesign the hotline section

### ISSUE THREAD

**Issue by jbienesdev** [covid19zc/covid19zc-website#33]
Follow this design

![image](https://user-images.githubusercontent.com/17470909/78418385-37a10100-766e-11ea-8b2f-f68c8151b2e9.png)

**Comment by JHNLWHD** [comment]
![image](https://user-images.githubusercontent.com/15794235/78470731-17e90600-775e-11ea-9dfb-46c662f1cb58.png)

QA Testing Passed 💯
