### ISSUE TITLE
Add illustration to the bottom right of the page

### ISSUE THREAD

**Issue by jbienesdev** [covid19zc/covid19zc-website#34]
![image](https://user-images.githubusercontent.com/17470909/78418405-5ef7ce00-766e-11ea-8723-00898a34adfb.png)

**Comment by JHNLWHD** [comment]
@jbienesdev Can I have the image/illustration file for this issue?

**Comment by jbienesdev** [comment]
@JHNLWHD  Sure. 

[virus(1) 1.svg.zip](https://github.com/covid19zc/covid19zc-website/files/4431028/virus.1.1.svg.zip)

**Comment by JHNLWHD** [comment]
![image](https://user-images.githubusercontent.com/15794235/78470684-d5272e00-775d-11ea-8da2-ff01f6e756c4.png)


QA Testing Passed 💯
