### ISSUE TITLE
Create the footer

### ISSUE THREAD

**Issue by jbienesdev** [covid19zc/covid19zc-website#35]
You can add the footer to `layouts/default.vue`

![image](https://user-images.githubusercontent.com/17470909/78418449-bd24b100-766e-11ea-8ddc-6a901b60225b.png)

**Comment by JHNLWHD** [comment]
![image](https://user-images.githubusercontent.com/15794235/78470716-f425c000-775d-11ea-8ccb-2f0d85071685.png)


QA Testing Passed 💯
