### ISSUE TITLE
Put content inside the accordion

### ISSUE THREAD

**Issue by jbienesdev** [covid19zc/covid19zc-website#4]
Populate accordion with hotline numbers.

**Zamboanga Task Force COVID-19**
<img width="797" alt="image" src="https://user-images.githubusercontent.com/17470909/77634657-46135c80-6f8c-11ea-8a03-b414b5b79a6e.png">

**Teleconsultation**
<img width="803" alt="image" src="https://user-images.githubusercontent.com/17470909/77634725-604d3a80-6f8c-11ea-9690-ae5efd4d2edd.png">

**Comment by jbienesdev** [comment]
Taking this issue

**Comment by JHNLWHD** [comment]
**Desktop:**
![image](https://user-images.githubusercontent.com/15794235/78086999-31065580-73f2-11ea-892f-917ec91dad80.png)
**Mobile:**
![image](https://user-images.githubusercontent.com/15794235/78087056-58f5b900-73f2-11ea-8585-aab7a721946c.png)
![image](https://user-images.githubusercontent.com/15794235/78087068-64e17b00-73f2-11ea-9a40-5ad2f36e325b.png)

QA Testing Passed 💯
