### ISSUE TITLE
Create under maintenance page

### ISSUE THREAD

**Issue by jbienesdev** [covid19zc/covid19zc-website#41]
Using this illustration

![image](https://user-images.githubusercontent.com/17470909/78424891-21f9fe80-76a3-11ea-9761-8c8b49b33dad.png)

**Comment by JHNLWHD** [comment]
![image](https://user-images.githubusercontent.com/15794235/78470769-6bf3ea80-775e-11ea-920e-a41a9c05e71d.png)

QA Testing Passed 💯
