### ISSUE TITLE
Fix responsiveness of hotline cards

### ISSUE THREAD

**Issue by jbienesdev** [covid19zc/covid19zc-website#43]
Fix responsiveness of cards between `lg` and `xl` devices.

**Comment by JHNLWHD** [comment]
![image](https://user-images.githubusercontent.com/15794235/78470793-9d6cb600-775e-11ea-959e-aa37edbc7a7d.png)
![image](https://user-images.githubusercontent.com/15794235/78470797-a6f61e00-775e-11ea-83be-2faafe558e7e.png)
![image](https://user-images.githubusercontent.com/15794235/78470803-ac536880-775e-11ea-89be-bd5dc5c31df0.png)
![image](https://user-images.githubusercontent.com/15794235/78470810-b4aba380-775e-11ea-91a9-8c896cf7f3d8.png)

QA Testing Passed 💯
