### ISSUE TITLE
Integrate Firebase temporarily

### ISSUE THREAD

**Issue by jbienesdev** [covid19zc/covid19zc-website#45]
Needed to avoid committing the data updates.

**Comment by JHNLWHD** [comment]
Just use the realtime DB feature.

**Comment by JHNLWHD** [comment]
![image](https://user-images.githubusercontent.com/15794235/78470847-0ce2a580-775f-11ea-85cf-c5e463b2f775.png)
![image](https://user-images.githubusercontent.com/15794235/78470856-1e2bb200-775f-11ea-9451-304045374502.png)

QA Testing Passed 💯
