### ISSUE TITLE
Add website title

### ISSUE THREAD

**Issue by jbienesdev** [covid19zc/covid19zc-website#5]
Add the website title based from this image

<img width="1153" alt="Frontpage jpg 2020-03-26 20-48-55" src="https://user-images.githubusercontent.com/17470909/77648540-423f0480-6fa3-11ea-9369-2398e4932ff9.png">

**Comment by JHNLWHD** [comment]
![image](https://user-images.githubusercontent.com/15794235/77854140-04e4ac00-721b-11ea-9563-53bc545f1564.png)

- Padding in the mobile view is being fixed in issue #9 requested in #11 .

QA Testing Passed 💯
