### ISSUE TITLE
Add "Last Updated" text

### ISSUE THREAD

**Issue by jbienesdev** [covid19zc/covid19zc-website#6]
Based from the mockup. The date should be ready to fetch data from the API.

<img width="1153" alt="Frontpage jpg 2020-03-26 20-59-14" src="https://user-images.githubusercontent.com/17470909/77649349-b0d09200-6fa4-11ea-9186-c352b7191643.png">

**Comment by JHNLWHD** [comment]
![image](https://user-images.githubusercontent.com/15794235/77854310-24c89f80-721c-11ea-89ce-b89082c75e49.png)

- Padding in the mobile view is being fixed in issue #9 requested in #11.

QA Testing Passed 💯
