### ISSUE TITLE
Make cards responsive

### ISSUE THREAD

**Issue by jbienesdev** [covid19zc/covid19zc-website#9]
Make the cards full width when it comes to medium to small screens.

![covid1](https://user-images.githubusercontent.com/17470909/77814963-f4381700-70f0-11ea-86ad-ab3af3c2e991.gif)

**Comment by JHNLWHD** [comment]
![image](https://user-images.githubusercontent.com/15794235/78011384-18585a00-7376-11ea-8b4a-546dd4fe408b.png)

QA Testing failed ❗️ ❗️ ❗️

**Comment by JHNLWHD** [comment]
![image](https://user-images.githubusercontent.com/15794235/78086860-c8b77400-73f1-11ea-8048-03d57327c117.png)

QA Testing Passed 💯 

Note: It has already achieved the responsiveness of every card in small devices and having just in line gaps between the cards.
